### ISSUE TITLE
Incorrect message size

### ISSUE THREAD

**Issue by ewhauser** [ExactTargetDev/kafka#4]
(Per Justin McKinley)

I’m having an issue with the .NET Kafka client where, it seems, the size of a message (of the payload) is incorrect. This seems to happens in the middle of the messages within a topic – i.e., I’m retrieving a batch of messages, and after a certain number of messages (I haven’t found a pattern yet), one message has an extremely high reported size – sometimes the size is 100kb, sometimes it can be up to 1.7Gb.

Here is the code that I see having the issue:

``` csharp
int msgSize = reader.ReadInt32();

readed += 4;

Message msg = Message.ParseFrom(reader, msgSize);
readed += msgSize;
messages.Add(msg);
```

The msgSize is what is incorrect. Note that when this problem occurs, msgSize is larger than the size variable passed in, which is presumably the size of the entire message packet. I added some code to try to fix it:

``` csharp
int msgSize = reader.ReadInt32();

readed += 4;

// jjmc - testing a fix
int sizeNotUsed = size - readed;
if (msgSize > sizeNotUsed) msgSize = sizeNotUsed;

Message msg = Message.ParseFrom(reader, msgSize);
readed += msgSize;
messages.Add(msg);
```

When my fix is executed (i.e, when the message size is extremely large), then there is still a problem – it seems as though the message is actually a set of multiple messages in one bunch (as if the message size is still not correct). That may just be a side effect of my “fix” – it may not be the correct fix.

**Comment by jmckinleyET** [comment]
Additions to my notes above:
- This problem is easily (for me) recreated when I add 1000-4000 messages to a topic, then attempt to retrieve them in batch sizes less than the total number of messages added to the topic. For example, I may add 3000 new messages to a topic, then begin reading it in batches of 200. After a few batches are retrieved, this problem may occur. Once it begins occurring for a particular test case, it always occurs.
- When the batch size is greater than the total number of messages in the topic, I don't seem to have this problem.

**Comment by mluban** [comment]
Essentially the same as #2.

**Comment by bosman** [comment]
Fixed. Please rerun tests on your side to confirm and close the ticket.

**Comment by jmckinleyET** [comment]
This problem still seems to be happening for me. See example screenshot: ![Message Size Error](http://i.imgur.com/PNSjw.jpg)

**Comment by ewhauser** [comment]
Just to confirm, you did rebuild the DLL and cleared out any old versions of it in your bin folder?

**Comment by jmckinleyET** [comment]
I actually just added the newer version of the client to the project, and changed references to use it. Note that the screenshot highlights the new code (meaning that at least, Visual studio thinks I'm using the updated code).
I will clear out and try again, to be sure.

-----Original Message-----

**Comment by bosman** [comment]
I found another possible flaw in the code and corrected it. It's committed. Please, see if this version works correctly. If not, then please provide a description of your test case or perhaps some code fragment that I could use to reproduce the issue.

**Comment by jmckinleyET** [comment]
This seems to be working for me. I've run the client a lot this morning, and haven't run into any problems.
Thank you!

-----Original Message-----
